const swaggerAutogen = require('swagger-autogen')()


const doc = {
    info: {
        version: "1.0.0",
        title: "MSCR datamodel API",
        description: "Documentation automatically generated by the <b>swagger-autogen</b> module."
    },
    host: "localhost:3000",
    basePath: "/",
    schemes: ['http', 'https'],
    consumes: ['application/json'],
    produces: ['application/json'],
    tags: [
        {
            "name": "Schema",
            "description": "Endpoints"
        },
        {
            "name": "Crosswalk",
            "description": "Endpoints"
        } 
    ],
    definitions: {
    }
}

const outputFile = './swagger_output.json'
const endpointsFiles = ['./src/endpoints.js']

swaggerAutogen(outputFile, endpointsFiles, doc).then(() => {
    require('./index')           // Your project's root file
})